#version: '3'
#services:
#  nginx:
#    build: ./nginx
#    image: #repository url
#    restart: always
#    ports:
#      - "80:80"
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: /var/log/nginx
#        awslogs-region: us-west-2
#        awslogs-stream-prefix: nginx
#    volumes:
#      - /srv/docker-server
#      - /var/log/nginx
#  django:
#    build: ./fastcampus
#    image: #repository url
#    restart: always
#    command: uwsgi --ini uwsgi.ini
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: /var/log/uwsgi
#        awslogs-region: us-west-2
#        awslogs-stream-prefix: django
#    volumes:
#      - /srv/docker-server
#      - /var/log/uwsgi

version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: docker-server/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./fastcampus:/srv/docker-server
      - ./log:/var/log/nginx
    depends_on:
      - django
  django:
    container_name: django
    build: ./fastcampus
    image: docker-server/django
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./fastcampus:/srv/docker-server
      - ./log:/var/log/uwsgi